### PR TITLE
Adding support for custom reports and some  fixes

### PR DESCRIPTION
**Pull request by ntiss**
Removing of unnecessary binding.

### CODE REVIEW

**Comment by ntiss** [comment]
- add support for custom reports
- fix for issue [#14](https://github.com/apigeecs/apigee-migrate-tool/issues/14) (deployProxies fails) 
- fix for exportAll PR #13

**Comment by ntiss** [comment]
Conflicts have been resolved.
PR is ready to be merged.

**Comment by anvi2206** [comment]
@shahbagdadi any update on when this PR can be merged. We are facing the same issue and would like to use fixed version asap.

**Comment by anvi2206** [comment]
@shahbagdadi will this be merged anytime soon?

**Comment by ntiss** [comment]
Hello @anvi2206 
Last merges on this project have been made by @stevetraut in October but I suppose that @shahbagdadi is able to merge this PR.
This current PR was not ready in October, there were conflicts that I've fixed later in December. 

If you can't wait to use this new feature, you can download from my fork here : [https://github.com/ntiss/apigee-migrate-tool](https://github.com/ntiss/apigee-migrate-tool)

**Pull request merged**
