### PR TITLE
Fix for issue #32 exportApps and #33 exportDevs

### PR DESCRIPTION
**Pull request by kurtkanaskie**
The iterateOverDevs function was calling done() when it needed to still wait for callbacks to finish.

Testing by adjusting the count param on GET /developers (default is 1000) for boundary conditions.
1. 0 developers
2. 1 developer, 1 app
3. 1 developer, 0 app
4. N developers, X apps (count = N-2, N-1, N, N+1, N+2)

### CODE REVIEW

**Comment by karsten-wagner** [comment]
Great! Works for me based on this PR:

**Comment by kurtkanaskie** [comment]
Up to here fixes for:
-  #32 exportApps and #33 exportDevs
-  #31, #18, KVM export, import and delete is now restricted to env in config.js, not all.

**Comment by kurtkanaskie** [comment]
Previously, KVMs tried to export all KVMs from all Environments, which didn't work because done() was being called prematurely. Now, it just exports the KVMs for the environment in config.js.

**Comment by kurtkanaskie** [comment]
Fixed importKeys, the flow to migrate Apps and their existing keys is:
exportApps - includes original keys
importApps - Edge ignores original keys and creates new keys, importApps then deletes those keys.
importKeys - to import original keys.

**Pull request merged**
